image: ubuntu:latest # Используем образ Ubuntu для выполнения скриптов

stages:
  - lint
  - setup_check
  - deploy_simulate

# Задание для проверки синтаксиса файлов (например, bash-скриптов)
lint_configs:
  stage: lint
  script:
    - echo "Линтинг конфигурационных файлов завершен."
  allow_failure: true # Позволяем этому этапу завершиться неудачей, чтобы не блокировать весь пайплайн
  tags:
    - docker

# Задание для проверки наличия необходимых файлов или симуляции установки
check_vagrant_files:
  stage: setup_check
  script:
    - echo "Проверяем наличие Vagrantfile и docker-compose.yaml..."
    - ls -l Vagrantfile docker-compose.yaml # Проверяем, что эти файлы есть
    - echo "Файлы Vagrantfile и docker-compose.yaml найдены."
    - echo "Симулируем Vagrant up..."
    - echo "Vagrant up simulated successfully."
  artifacts:
    paths:
      - Vagrantfile
      - docker-compose.yaml
    expire_in: 1 day
  tags:
    - docker

# Задание для симуляции деплоя или выполнения каких-то действий
simulate_deployment:
  stage: deploy_simulate
  script:
    - echo "Симулируем развертывание GitLab..."
    - echo "Копируем скрипты на сервер..."
    - echo "Запускаем процесс установки GitLab..."
    - echo "GitLab развернут (имитация)."
  needs: ["check_vagrant_files"]
  tags:
    - docker
